/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_qylk_media_ApicFromTag */

#ifndef _Included_cn_qylk_media_ArtistInfo_ApicFromTag
#define _Included_cn_qylk_media_ArtistInfo_ApicFromTag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_qylk_media_ArtistInfo_ApicFromTag
 * Method:    ApicFromTag
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_qylk_media_ArtistInfo_ApicFromTag
(JNIEnv *, jobject, jstring, jstring);
#ifdef __cplusplus
}
#endif
#endif
