/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_qylk_FeedBackUI */

#ifndef _Included_cn_qylk_FeedBackUI
#define _Included_cn_qylk_FeedBackUI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_qylk_FeedBackUI
 * Method:    FeedBack
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean Java_cn_qylk_FeedBackUI_FeedBack(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
