/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_qylk_media_ArtistInfo */

#ifndef _Included_cn_qylk_media_ArtistInfo
#define _Included_cn_qylk_media_ArtistInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_qylk_media_ArtistInfo
 * Method:    ApicFromTag
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean Java_cn_qylk_lrc_MediaLyric_LyricFromTag
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
