/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_qylk_media_ArtistInfo */

#ifndef _Included_cn_qylk_app_APPUtils
#define _Included_cn_qylk_app_APPUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn.qylk.app.APPUtils
 * Method:    SaveToID3v2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT void Java_cn_qylk_app_APPUtils_SaveToID3v2
  (JNIEnv *, jobject, jstring,jstring,jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
