/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_cn_qylk_utils_ID3
#define _Included_cn_qylk_utils_ID3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn.qylk.utils
 * Method:    SaveToID3v2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT void Java_cn_qylk_utils_ID3_SaveToID3v2
  (JNIEnv *, jobject, jstring,jstring,jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
